belevets/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('pleinair/', include('pleinair.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('course.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belevets/base/urls.py
from django.urls import path
from . import views


app_name = 'base'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

belevets/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('<int:pk>/', views.ArticleView.as_view(), name='article'),
]

belevets/contact/urls.py
from django.urls import path
from .views import ContactView, PleinAirView, thanks


app_name = 'contact'

urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
    path('thanks/', thanks, name='thanks'),
    path('<int:pk>/', PleinAirView.as_view(), name='pleinair'),
]

belevets/course/urls.py
from django.urls import path
from .views import CoursesView, PublicCourseDetailView, PrivateCourseDetailView, CourseDetailView


app_name = 'course'
urlpatterns = [
    path('', CoursesView.as_view(), name='courses'),
    path('<int:pk>/', CourseDetailView.as_view(), name='course'),
]

belevets/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('order/<int:pk>/', views.order, name='add_order'),
    path('cancel/', views.cancel_order, name='cancel'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete/', views.payment_complete, name='complete'),
]

belevets/base/models.py
from django.db import models

# Create your models here.

belevets/base/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'base/index.html')


def about(request):
    return render(request, 'base/about.html')

belevets/base/templates/base/about.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
  <div class="row">
      <div class="col-md-6">
        <h5>What I am doing</h4>
        <p>Have you ever felt tired of visual information? If there is a sense of oversaturation, objects can leave my paintings, so all that's left are only lines, color spots, emotions and pure energy. But sometimes an object's form is more important and significant to me, so I do focus on it more and show it brightly and hyperbolically using the same tools as lines and spots.</p>  
        <h5>How I do work</h4>
        <p>I'm working in an expressive-impulsive manner, I am not afraid of mixing structures and chaos, strictly showing my character and attitude towards life.</p>
        <p>If I get any strong emotion from an object or view I saw, I need to portray it as soon as possible, without any delay for days. During my work time, I do not notice anything around. A fast manner requires a strong concentration.</p>
        <h5>My technique</h4>
        <p>In my works I use multi-layer painting. First, I make a structural composition of large color spots. Such fillings are divided into several layers. Later, using graphics, I set the direction and the tempo of the viewer's eye movement. I use watercolor, acrylic, pastel, charcoal, liners and markers. I’m not afraid to mix all this in one picture. So I’m usually staying between figurative and abstraction.</p>
      </div>
      <div class="col-md-6">
        <img src="{% static 'base/images/volha.webp' %}">
      </div>
  </div> 
{% endblock %}

belevets/base/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'base/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'base/css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">

    <!-- Bootstrap for carousel -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Art Studio of Volha Belevets</title>

  </head>
  <body>

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>

      <div class="top-bar">
        <div class="container">
          <div class="row">
            <div class="col-8">
              <div class="float-right">
                <a href="#" class=""><span class="mr-2  icon-twitter"></span> <span class="d-none d-md-inline-block">Twitter</span></a>
                <span class="mx-md-2 d-inline-block"></span>
                <a href="#" class=""><span class="mr-2  icon-facebook"></span> <span class="d-none d-md-inline-block">Facebook</span></a>
                <span class="mx-md-2 d-inline-block"></span>
                <a href="#" class=""><span class="mr-2  icon-youtube"></span> <span class="d-none d-md-inline-block">YouTube</span></a>
                <span class="mx-md-2 d-inline-block"></span>
                <a href="#" class=""><span class="mr-2  icon-instagram"></span> <span class="d-none d-md-inline-block">Instagram</span></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="site-logo container">
              <a href="{% url 'base:index' %}" class="text-black"><span class="text-info">Volha Belevets</a>
            </div>

            <div class="col-12">
              <nav class="site-navigation text-right ml-auto " role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                  <li><a href="{% url 'course:courses' %}" class="nav-link">Courses</a></li>
                  <li><a href="{% url 'pleinair:pleinair' %}" class="nav-link">PleinAir</a></li>
                  <li><a href="{% url 'base:about' %}" class="nav-link">About me</a></li>
                  <li><a href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li>
                  <li><a href="{% url 'contact:contact' %}" class="nav-link">Contact</a></li>
                  <li><a href="{% url 'users:dashboard' %}" class="nav-link">
                    {% if user.is_authenticated %}
                      My account: {{ user.username }}
                    {% else %}
                      Log in
                    {% endif %}
                    </a></li>
                </ul>
              </nav>
            </div>
            <div class="toggle-button d-inline-block d-lg-none"><a href="#" class="site-menu-toggle py-5 js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
          </div>
        </div>
      </header>

    <script src="{% static 'base/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'base/js/main.js' %}"></script>
    <div class="block-content">
      {% block content %}
      {% endblock %}
    </div>
    <div class="row mt-10 mb-10">
      <p>.</p>
    </div>
    <div class="block-content">
      <div class="col">
        
        <a class="my_link" href="https://www.artfinder.com/artist/volha-belevets" onclick="window.open('https://www.artfinder.com/artist/volha-belevets','name','width=800,height=600')">
          <h4 style="text-align:center">My artist's work shop</h4>
          <div id="carouselSlideOnly" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'base/images/carousel1.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'base/images/carousel2.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'base/images/carousel3.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'base/images/carousel4.png' %}" class="d-block w-100" alt="...">
              </div>
            </div>
          </div>
        </a>  
      </div>
    </body>
  </div>
</html>

belevets/base/templates/base/index.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
    <div class="hero" style="background-image: url({% static 'base/images/main.png' %});"></div>
{% endblock %}