belevets/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('pleinair/', include('pleinair.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('course.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belevets/contact/urls.py
from django.urls import path
from .views import ContactView, PleinAirView, thanks


app_name = 'contact'

urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
    path('thanks/', thanks, name='thanks'),
    path('<int:pk>/', PleinAirView.as_view(), name='pleinair'),
]

belevets/pleinair/urls.py
from django.urls import path
from . import views


app_name = 'pleinair'

urlpatterns = [
    path('', views.PleinairView.as_view(), name='pleinair'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
]

belevets/pleinair/models.py
from django.db import models


class PleinAir(models.Model):
    title = models.CharField(max_length=100)
    advt = models.CharField(max_length=200)
    description = models.TextField()
    start = models.DateTimeField()
    duration = models.CharField(max_length=50)
    place = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.FileField(upload_to='pleinair/images', blank=True)

    def __str__(self):
        return self.title

belevets/pleinair/views.py
from django.utils import timezone
from django.views import generic

from .models import PleinAir


class PleinairView(generic.ListView):
    model = PleinAir
    template_name = 'pleinair/pleinairs.html'
    context_object_name = 'pleinairs'

    def get_queryset(self):
        pleinairs = super().get_queryset()
        pleinair_future = []
        for pleinair in pleinairs:
            if pleinair.start > timezone.now():
                pleinair_future.append(pleinair)
        return pleinair_future


class DetailView(generic.DetailView):
    model = PleinAir
    template_name = 'pleinair/details.html'
    context_object_name = 'pleinair'

belevets/pleinair/templates/pleinair/details.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}

    <div class="row bg-info">
        <div class="row">
            <div class="col-md-5">
                <img class="card-img-top p-3" src="{{MEDIA_URL}}{{pleinair.image}}" alt="screen">
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    <div class="p-2 mb-2 bg-white ">
                        <p class="card-text">{{ pleinair.title }}</p>
                        <p class="card-text">{{ pleinair.description }}</p> 
                        <p class="card-text"><b>Start: </b> {{ pleinair.start }}</p> 
                        <p class="card-text"><b>Duration: </b> {{ pleinair.duration }}</p> 
                        <p class="card-text"><b>Place: </b>{{ pleinair.place }}</p> 
                        <p class="card-text"><b>Price: </b>{{ pleinair.price }}</p>
                        <a href="{% url 'contact:pleinair' pleinair.pk %}" class="btn btn-info">Participate</a> <!--TODO Send to contact_us with message pleinari.title-->           
                    </div>
                </div>
            </div>        
        </div>
    </div>

{% endblock %}

belevets/pleinair/templates/pleinair/pleinairs.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="row bg-info">
    {% for pleinair in pleinairs %}
        <div class="col-md-4 mt-2">
            <div class="p-3 mb-2 bg-white text-black">
                <h5 class="card-title">{{ pleinair.title }}</h5>
                <img class="card-img-top" src="{{MEDIA_URL}}{{pleinair.image}}" alt="screen">
                <div class="card-body">
                    <p class="card-text">{{ pleinair.advt }}</p>
                    <p><span><b>Start: </b></span><span class="card-text">{{ pleinair.start }}</span></p>
                    <p><span><b>Duration: </b></span><span class="card-text">{{ pleinair.duration }}</span></p>
                    <p><span><b>Place: </b></span><span class="card-text">{{ pleinair.place }}</span></p>
                    <a href="{% url 'pleinair:details' pleinair.pk %}" class="btn btn-info">Details</a>               
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}