belevets/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('pleinair/', include('pleinair.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('course.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belevets/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('order/<int:pk>/', views.order, name='add_order'),
    path('cancel/', views.cancel_order, name='cancel'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete/', views.payment_complete, name='complete'),
]

belevets/users/models.py
from django.db import models
from django.db.models import CASCADE
from django.contrib.auth.models import User
from django.utils import timezone

from blog.models import Blog, Comment
from course.models import Course


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    likes = models.ManyToManyField(Blog)
    comment = models.ManyToManyField(Comment)
    course = models.ManyToManyField(Course)

    def __str__(self):
        return self.user.username


class Order(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=CASCADE)
    courses = models.ManyToManyField(Course)
    payment = models.BooleanField(default=False)
    date = models.DateTimeField(default=timezone.now)

belevets/users/forms.py
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email', 'username')

belevets/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.urls import reverse
import json
from django.core.exceptions import ObjectDoesNotExist

from users.forms import CustomUserCreationForm
from users.models import UserProfile, Order
from course.models import Course


def register(request):
    if request.method == 'GET':
        return render(
            request, 'users/register.html',
            {'form': CustomUserCreationForm}
        )
    elif request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            user.save()
            user_profile = UserProfile.objects.create(user=user)
            user_profile.save()
            login(request, user)
            return redirect(reverse('users:dashboard'))
        else:
            return render(
                request, 'users/register.html',
                {'form': CustomUserCreationForm, 'errors': form.errors.values(), }
            )
    return redirect(reverse('users:register'))


def dashboard(request, *args, **kwargs):
    if request.user.is_authenticated:
        # Just users who passed registration formcan access (admin fromc reatesuperuser - cant)
        try:
            user = request.user.userprofile
        except ObjectDoesNotExist:
            return render(request, 'users/dashboard.html')

        courses = user.course.all()
        try:
            order = Order.objects.get(user=user, payment=False)
            ordered_courses = order.courses.all()
            amount = 0
            for course in ordered_courses:
                amount += course.price
        except (AttributeError, ObjectDoesNotExist):
            order = None
            ordered_courses = None
            amount = 0

        context = {
            'courses': courses,
            'ordered_courses': ordered_courses,
            'amount': amount,
        }
    else:
        # Template is_authenticated=False part will work
        context = None
    return render(request, 'users/dashboard.html', context)


def order(request, pk):  # TODO check with several courses in order
    if request.user.is_authenticated:
        user = UserProfile.objects.get(user=request.user)
        try:
            order = Order.objects.get(user=user, payment=False)
            order.courses.add(Course.objects.get(pk=pk))
        except (ObjectDoesNotExist, AttributeError):
            order = Order.objects.create(user=user)
            order.courses.set([Course.objects.get(pk=pk)])
            order.save()
    return dashboard(request)


def cancel_order(request):
    user = UserProfile.objects.get(user=request.user)
    try:
        order = Order.objects.get(user=user, payment=False)
        order.delete()
    except ObjectDoesNotExist:
        pass
    return dashboard(request)


# PayPal Payment
def checkout(request):
    if request.user.is_authenticated:
        user = request.user.userprofile
        courses = user.course.all()
        try:
            order = Order.objects.get(user=user, payment=False)
            amount = 0
            for obj in order.courses.all():
                amount += obj.price
            ordered_courses = order.courses.all()
            context = {
                'courses': courses,
                'ordered_courses': ordered_courses,
                'order': order,
                'amount': amount,
            }
        except ObjectDoesNotExist:
            context = {
                'courses': courses,
                'amount': 0,
            }
            return render(request, 'users/dashboard.html', context)
    else:
        # Template is_authenticated part will work
        context = None
    return render(request, 'users/checkout.html', context)


def payment_complete(request):
    body = json.loads(request.body)
    user = request.user.userprofile
    order = Order.objects.get(pk=body['orderID'])
    order.payment = True
    order.save()
    courses = order.courses.all()
    for course in courses:
        user.course.add(course)
    return dashboard(request)

belevets/users/templates/users/checkout.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<header>
    <meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <style>
        p {color:black;
            margin: 2px;
            text-align: left ;}
        .my_link {color:#17929b;
            margin-left: 5px;
            text-align: left;
            width: 100%;
            padding-left: 15;
        }
        li {color:#17929b;
            list-style-type: none;
            text-align: left;
            padding-left: none;
        }
    </style>
</header>

<div class="container p-20 m-20 d-flex justify-content-center">
    <div class="col bg-light">
        <div class="row p-2 text-dark ">Welcome,&nbsp&nbsp<b>{{ user.username|default:"Guest" }}!</b></div>
        <div class="w-100"></div>
        {% if user.is_authenticated %}
            <div class="row mt-2">
                <div class="col-2">My active courses:</div>
                <div class="col-6">
                {% for course in courses %}
                    <p>{{ course }}</p>
                {% endfor %}
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-2">My order:</div>
                <div class="col-6">
                {% for course in ordered_courses %}
                    <p>{{ course.title }}</p>
                {% endfor %}
                </div>
            </div>
            <div class="row mt-3">
                <p>Total to pay: {{ amount }} €</p>
            </div>
            <div class="row m-3">
                <div id="paypal-button-container"></div>
            </div>
            <div class="row m-3 mt-1">
                <a href="{% url 'users:cancel' %}" class="btn btn-dark p-2">Cancel order</a>
            </div>
            <div class="row mt-4"><p><a class="my_link" href="{% url 'password_change' %}">Change password</a></p></div>
            <div class="row mt-3 mb-3"><p><a class="my_link" href="{% url 'logout' %}">Logout</a></p></div>
        {% else %}
        <div class="w-100"></div>
        <div class="row mt-2 align-items-start">
            <div class="col-sm-1 m-3">
                <a href="{% url 'login' %}" class="btn btn-info p-2"> Login </a>
            </div>
            <div class="col-sm-3 m-3">
                <a href="{% url 'users:register' %}" class="btn btn-dark p-2">Sign in</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
<script src="https://www.paypal.com/sdk/js?client-id=AfodFRKlmYOPkJG1eq9RbUS89JmhwIcEp8BAz6pP8thSxkCqTCOgiMgJuD3i0OFrHmWKLqqJW0i0jLHG&currency=EUR&disable-funding=credit,sofort"></script>
<script>
    var total = '{{ amount }}';
    var orderId = '{{ order.id }}';

    function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    function completeOrder(){
        var url = "{% url 'users:complete' %}"
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-type':'aplication/json',
                'X-CSRFToken':csrftoken,
            },
            body:JSON.stringify({'orderID':orderId})
        })
    };
    paypal.Buttons({
        // Render PayPal button to paypal-button-container
        style: {
            color:  'silver',
            shape:  'rect',
            label:  'pay',
            height: 40
        },

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: total
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                completeOrder()
                alert('Transaction completed by ' + details.payer.name.given_name + '!\nTank you for your payment!');
            });
        }

    }).render('#paypal-button-container');
</script>
{% endblock %}


    

belevets/users/templates/users/dashboard.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<header>
    <style>
        p {color:black;
            margin: 2px;
            text-align: left ;}
        .my_link {color:#17929b;
            margin-left: 5px;
            text-align: left;
            width: 100%;
            padding-left: 15;
        }
        li {color:#17929b;
            list-style-type: none;
            text-align: left;
            padding-left: none;
        }
    </style>
</header>

<div class="container p-20 m-20 d-flex justify-content-center">
    <div class="col bg-light">
        <div class="row p-2 text-dark ">Welcome,&nbsp&nbsp<b>{{ user.username|default:"Guest" }}!</b></div>
        <div class="w-100"></div>
        {% if user.is_authenticated %}
            <div class="row mt-2">
                <div class="col-2">My active courses:</div>
                <div class="col-6">
                {% for course in courses %}
                    <p>{{ course }}</p>
                {% endfor %}
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-2">My order:</div>
                <div class="col-6">
                {% for course in ordered_courses %}
                    <p>{{ course }}</p>
                {% endfor %}
                </div>
            </div>
            <div class="row mt-3">
                <p>Total to pay: {{ amount }} €</p>
            </div>
            <div class="row mt-3 col-4 mb-2 align-items-start">
                <div class="m-3">
                    <a href="{% url 'users:checkout' %}" class="btn btn-info p-2">Pay and checkout</a>
                </div>
                <div class="m-3">
                    <a href="{% url 'users:cancel' %}" class="btn btn-dark p-2">Cancel order</a>
                </div>
            </div>
            <div class="row mt-3"><p><a class="my_link" href="{% url 'password_change' %}">Change password</a></p></div>
            <div class="row mt-3 mb-3"><p><a class="my_link" href="{% url 'logout' %}">Logout</a></p></div>
        {% else %}
        <div class="w-100"></div>
        <div class="row mt-2 align-items-start">
            <div class="col-sm-1 m-3">
                <a href="{% url 'login' %}" class="btn btn-info p-2"> Login </a>
            </div>
            <div class="col-sm-3 m-3">
                <a href="{% url 'users:register' %}" class="btn btn-dark p-2">Sign in</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

belevets/users/templates/users/register.html
{% extends 'base/base.html' %}

{% block content %}
<header>
    <style>
        p {color:black;
            margin: 2px;
            text-align: left ;}
        .my_link {color:#17929b;
            margin-left: 5px;
            text-align: left;
            width: 100%;
            padding-left: 15;
        }
        li {color:#17929b;
            list-style-type: none;
            text-align: left;
            padding-left: none;
        }
    </style>
</header>
<div class="container bg-light p-4">
    <div class="row text-dark justify-content-start"><h4>Registration form</h4></div>
    <div class="row col-6">
        {% if errors %}
            <p>Wrong form: </p>
            {% for error in errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
    </div>
    <form method="post">
        {% csrf_token %}
        <p>{{ form.username.label }}</p>
        <p>{{ form.username }}</p>
        <p>{{ form.email.label }}</p>
        <p>{{ form.email }}</p>
        <p>{{ form.password1.label }}</p>
        <p>{{ form.password1 }}</p>
        <p>{{ form.password2.label }}</p>
        <p>{{ form.password2 }}</p>
        <input type="submit" class="col-md-2 mt-1 ml-3 mt-3 btn btn-info p-1" value="Registration">
    </form>

    <div class="row col mt-3">
        <a class="my_link" href="{% url 'login' %}">Back to dashboard</a>
    </div>
</div>
{% endblock %}