belevets/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('pleinair/', include('pleinair.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls')),
    path('courses/', include('course.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belevets/course/urls.py
from django.urls import path
from .views import CoursesView, PublicCourseDetailView, PrivateCourseDetailView, CourseDetailView


app_name = 'course'
urlpatterns = [
    path('', CoursesView.as_view(), name='courses'),
    path('<int:pk>/', CourseDetailView.as_view(), name='course'),
]

belevets/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('order/<int:pk>/', views.order, name='add_order'),
    path('cancel/', views.cancel_order, name='cancel'),
    path('checkout/', views.checkout, name='checkout'),
    path('complete/', views.payment_complete, name='complete'),
]

belevets/course/models.py
from django.db.models.deletion import CASCADE
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=100)
    description_public = models.TextField()
    description_private = models.TextField(blank=True)
    announcement = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.FileField(upload_to='course/images', blank=True)
    video = models.FileField(upload_to='course/video', blank=True)

    def __str__(self):
        return self.title


class Section(models.Model):
    course = models.ForeignKey(Course, on_delete=CASCADE)
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100, blank=True)
    image = models.FileField(upload_to='course/imges', blank=True)
    text = models.TextField(blank=True)
    materials = models.TextField(blank=True)

    def __str__(self):
        return f"{self.course}, {self.title}"


class Lesson(models.Model):
    section = models.ForeignKey(Section, on_delete=CASCADE)
    title = models.CharField(max_length=100)
    number = models.CharField(max_length=50)
    text = models.TextField(blank=True)
    image = models.FileField(upload_to='course/imges', blank=True)
    video = models.FileField(upload_to='course/video', blank=True)

    def __str__(self):
        return f"{self.title}, {self.section}"

belevets/course/views.py
from django.views import generic, View

from .models import Course, Section, Lesson


class CoursesView(generic.ListView):
    model = Course
    template_name = 'course/courses.html'
    context_object_name = 'courses'


class PublicCourseDetailView(generic.DetailView):
    model = Course
    template_name = 'course/course_public.html'

    def get_context_data(self, *args, **kwargs):
        course = Course.objects.get(pk=int(kwargs['object'].pk))
        sections = Section.objects.filter(course=course)
        for section in sections:
            section.lessons = Lesson.objects.filter(section=section)
        context = {
            'course': course,
            'sections': sections
        }
        return context


class PrivateCourseDetailView(generic.DetailView):
    model = Course
    template_name = 'course/course_private.html'
    context_object_name = 'course'

    def get_context_data(self, *args, **kwargs):
        course = Course.objects.get(pk=int(kwargs['object'].pk))
        sections = Section.objects.filter(course=course)
        for section in sections:
            section.lessons = Lesson.objects.filter(section=section)
        context = {
            'course': course,
            'sections': sections
        }
        return context


class CourseDetailView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            course = Course.objects.get(pk=self.kwargs['pk'])
            user_courses = request.user.userprofile.course.all()
            if course in user_courses:
                view = PrivateCourseDetailView.as_view()
                return view(request, *args, **kwargs)
        view = PublicCourseDetailView.as_view()
        return view(request, *args, **kwargs)

belevets/course/templates/course/course_private.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="container bg-light  ">
    <div class="row justify-content-center">
        <div class="col-8 col-sm-12">
            <h5 class="text-center text-dark">{{ course.title }}</h5>
            <p class="text-center text-dark">{{ course.description_private }}</p>   
        </div>
    </div>
    {% for section in sections %}
        <div class="card mt-5" style="max-width: 80;">
            <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ MEDIA_URL }}{{ section.image }}" class="img-fluid rounded-start p-3" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                <h5 class="card-title">{{ section.title }}</h5>
                <h6 class="card-title pb-2">Materials:</h6>
                <p class="card-text">{{ section.materials|linebreaks}}</p>
                </div>
            </div>
            </div>
        </div>
        <div>
            {% for lesson in section.lessons %}
                <div>
                    <h5 class="card-title p-3">{{ lesson.number }}</h5>
                    <h7 class="card-title p-3">{{ lesson.title }}</h7>
                    <div id="elem" class="mt-5 mb-5 embed-responsive embed-responsive-16by9">    
                        <video controls width="250" oncontextmenu="return false;" controlsList="nodownload">
                            <source src="{{ MEDIA_URL }}{{ lesson.video }}" type="video/mp4" prelod="none">
                        </video>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

belevets/course/templates/course/course_public.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="container bg-light p-4">
    <div class="row justify-content-center">
        <div class="col-8 col-sm-12">
            <h5 class="text-center text-dark">{{ course.title }}</h5>
            <p class="text-center text-dark">{{ course.description_public }}</p>
            <div id="elem" class="embed-responsive embed-responsive-16by9">    
                <video controls width="250" oncontextmenu="return false;" controlsList="nodownload">
                    <source src="{{ MEDIA_URL }}{{ course.video }}" type="video/mp4">
                </video>
            </div>
        </div>
    </div>
    <div class="row mt-5 justify-content-center">
        {% if course.price == 0 %}
            <a href="#" class="btn btn-info">Free course</a>
        {% else %}
            <a href="{% url 'users:add_order' course.pk %}" class="btn btn-info">Place to my order - {{ course.price }} €</a>
        {% endif %}
    </div>
    <div class="row justify-content-center">
        {% for section in sections %}
            <div class="col-8 col-sm-12 p-5">
                <h5 class="p-3">{{ section.title }}</h5>       
                {% for lesson in section.lessons %}
                    <h6 class="p-3">{{ lesson.title }}</h6>
                    <div class="card" style="width: 25rem;">
                        <img class="card-img-center p-2" src="{{ MEDIA_URL }}{{ lesson.image }}" alt="screen">
                    </div>
                {% endfor %}
            </div>
        {% endfor %} 
</div>

{% endblock %}

belevets/course/templates/course/courses.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="row bg-info">
    {% for course in courses %}
        <div class="col-md-4 mt-2">
            <div class="card text-center p-2 mb-2 bg-white text-black">
                <h5 class="card-title">{{ course.title }}</h5>
                <img class="card-img-top" src="{{MEDIA_URL}}{{course.image}}" alt="screen">
                <div class="card-body">
                        <p>{{ course.announcement }}</p>
                    <div>
                        <a href="{% url 'course:course' course.pk %}" class="btn btn-info">I would like to know more</a>               
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}